import {
  Home,
  ReceiptText,
  Plus,
  ArrowLeftRight,
  Settings,
  Search,
  House,
  Palmtree,
  Users,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ShoppingCart,
  Pill,
  Utensils,
  Package,
  Camera,
  UserPlus,
  Ellipsis,
  Pencil,
  Trash2,
  SlidersHorizontal,
  CircleCheck,
  GitMerge,
  ArrowRight,
  Info,
  QrCode,
  Copy,
  Share2,
  Bell,
  Palette,
  Coins,
  Download,
  CircleHelp,
  LogOut,
  StickyNote,
  TrainFront,
  Zap,
  Tag,
  Mail,
  Lock,
  type LucideIcon,
} from "lucide-react";

/** design.html の data-lucide 名 -> コンポーネント */
const ICONS: Record<string, LucideIcon> = {
  home: Home,
  "receipt-text": ReceiptText,
  plus: Plus,
  "arrow-left-right": ArrowLeftRight,
  settings: Settings,
  search: Search,
  house: House,
  palmtree: Palmtree,
  users: Users,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "shopping-cart": ShoppingCart,
  pill: Pill,
  utensils: Utensils,
  package: Package,
  camera: Camera,
  "user-plus": UserPlus,
  "more-horizontal": Ellipsis,
  pencil: Pencil,
  "trash-2": Trash2,
  "sliders-horizontal": SlidersHorizontal,
  "circle-check": CircleCheck,
  "git-merge": GitMerge,
  "arrow-right": ArrowRight,
  info: Info,
  "qr-code": QrCode,
  copy: Copy,
  "share-2": Share2,
  bell: Bell,
  palette: Palette,
  coins: Coins,
  download: Download,
  "circle-help": CircleHelp,
  "log-out": LogOut,
  "sticky-note": StickyNote,
  "train-front": TrainFront,
  zap: Zap,
  tag: Tag,
  mail: Mail,
  lock: Lock,
};

export type IconName = keyof typeof ICONS | string;

export function Icon({
  name,
  size = 20,
  className,
  strokeWidth = 2,
}: {
  name: IconName;
  size?: number;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = ICONS[name] ?? Tag;
  return <Cmp size={size} className={className} strokeWidth={strokeWidth} aria-hidden />;
}
